### ISSUE TITLE
Find out what this returns: $this->request->server['HTTPS']

### ISSUE THREAD

**Issue by lucasjkr** [lucasjkr/opencommerce#21]
I'm thinking this isn't needed (probably to do with the request method), but need to check. It's referred to in several places, need to determine whether it returns "true", a URL, or something else

/catalog/controller/common/language.php

/catalog/controller/common/controller.php

And others

**Comment by arnisjuraga** [comment]
`catalog/controller/common/language.php` is loaded into `header.php` as language switcher, if you have more then one language added to site. 
I have changed that to just seo url link "/en" or "/de", instead of `<form action="{{ action }}" method="post" enctype="multipart/form-data" id="form-language">`, because POST method does not change not-seo url at all and is very bad for search bots - as you have the same link with different contents. 

`/catalog/controller/common/controller.php` - there is no such file..

**Comment by arnisjuraga** [comment]
What you need, most probably ,is this?
https://github.com/copona/copona/blob/55565350479140087eba90800862b6732f75f23a/system/startup.php#L127

**Comment by lucasjkr** [comment]
Resolved. Just didn't need the 3rd parameter in URL->link
